name: Test compilation

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opam_file:
          - 'coq-malfunction.opam'
        coq_version:
          - '8.17'
        ocaml_version: ['4.13-flambda']
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: coq-community/docker-coq-action@v1
        with:
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          opam_file: ${{ matrix.opam_file }}
          before_install: |
            startGroup "fix permission issues"
              sudo chown -R coq:coq .
            endGroup
            startGroup "opam pin"
              opam pin -n -y "https://github.com/MetaCoq/metacoq.git#1e3d82"
              opam pin -n -y "https://github.com/yforster/malfunction.git#for-pack"
            endGroup
          before_script: |
            startGroup "fix permission issues"
              sudo chown -R coq:coq .
            endGroup
          after_script: |
            startGroup "List installed packages"
              opam list
            endGroup
            startGroup "run tests"
              make -C benchmarks
            endGroup
