name: Test compilation

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opam_file:
          - 'coq-malfunction.opam'
        image:
          - 'yforster/coq:8.17.0--clang-11--compcert-3.12--extlib-0.11.8--equations-1.3--elpi.1.17.1-metacoq-8.17.dev.b33a9bd'
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: ${{ matrix.image }}
          opam_file: ${{ matrix.opam_file }}
          before_install: |
            startGroup "fix permission issues"
              sudo chown -R coq:coq .
            endGroup
            startGroup "opam pin"
              opam pin -n -y "https://github.com/mattam82/malfunction.git#packages-and-dontlink-for-compile"
              opam pin -n -y "https://github.com/MetaCoq/metacoq.git#eb2bf62"
            endGroup
          after_install: |
            startGroup "make"
              make -j 2 bootstrap
            endGroup
          script: |
            startGroup "fix permission issues"
              sudo chown -R coq:coq .
            endGroup
          after_script: |
            startGroup "List installed packages"
              opam list
            endGroup
            startGroup "run tests"
              make -C examples
              make -C benchmarks
            endGroup
