name: Test compilation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opam_file:
          - 'opam'
        image:
          - 'mattam82/coq:8.17--ocaml-4.13.1--clang-11--compcert-3.12--extlib-0.11.8--equations-1.3'
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: ${{ matrix.image }}
          opam_file: ${{ matrix.opam_file }}
          before_install: |
            startGroup "fix permission issues"
              sudo chown -R coq:coq .
            endGroup
            startGroup "opam pin"
              opam pin add coq-metacoq-erasure "https://github.com/MetaCoq/metacoq.git#coq-8.17"
              opam pin add coq-ceres "https://github.com/lysxia/coq-ceres.git#master"
            endGroup
          after_script: |
            startGroup "List installed packages"
              opam list
            endGroup
